language: php
services:
- elasticsearch
- mysql
matrix:
  include:
  - php: '5.3'
    env: VERSION=6.5.25 EDITION=Ent TESTS=6.5
  - php: '5.6'
    env: VERSION=7.8.0.1 EDITION=Ent TESTS=7.8
  - php: '5.6'
    env: VERSION=7.7.2.1 EDITION=Ent TESTS=7.7
before_install:
- echo "error_reporting = E_ALL & ~E_NOTICE & ~E_STRICT" >> ~/.phpenv/versions/$(phpenv
  version-name)/etc/php.ini
- sudo apt-get purge elasticsearch
- sudo curl -O https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.4.4.deb
- sudo dpkg -i --force-confnew elasticsearch-1.4.4.deb
- sudo service elasticsearch restart
- curl https://scarlett.sugarondemand.com/custom/hosted/encrypt.tar.gz.enc -o encrypt.tar.gz.enc
- openssl aes-256-cbc -k "$super_secret_password" -in encrypt.tar.gz.enc -out encrypt.tar.gz
  -d
- tar -xzvf encrypt.tar.gz
before_script:
- composer install
- unzip encrypt/Installers/$VERSION/Sugar$EDITION-$VERSION.zip &> /dev/null
- cp -R encrypt/Tests/$TESTS/ Sugar$EDITION-Full-$VERSION/tests/
- cp .travis/config_si.php Sugar$EDITION-Full-$VERSION/config_si.php
- cp .travis/cliSilentInstall.php Sugar$EDITION-Full-$VERSION/cliSilentInstall.php
- mysql -u root -e "CREATE USER 'sugarcrm'@'localhost' IDENTIFIED BY 'sugarcrm'"
- mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO 'sugarcrm'@'localhost' WITH GRANT
  OPTION;"
- sudo chmod -R 777 Sugar$EDITION-Full-$VERSION
- mv -f Sugar$EDITION-Full-$VERSION sugar
- cd sugar
- sleep 10
- php cliSilentInstall.php
- sudo chmod -R 777 .
- cd ..
script: vendor/bin/phpunit --coverage-clover build/logs/clover.xml
env:
  global:
    secure: cE1UK0J/EaVPxSG6qr6NEBYEOuBk+iR0CTlrgibpmJVkOWr34gu+HfsZSh4YvktkKLsGHJu2O4GeIGMAWnic/87+eWpeURXd5w1z14WgYpbDnL1h+TnZhjMJG9FRnmV1/5Krk9NxvIkHBWl3c9FuiCBQ88ZpmRDcxHauefftZoLqqrIq7kmQ7KHUzeWi1tUn7Ft+a56vmdajeGnKkPeLDix9wOeibDj6mDk4CeB5QeMB0APw4pjceAExfYMJcBjBshXD2GblmrW3j7OH4YSgSaYSR5DtRiOv2CjMfIr/jOHqMQn7dJzEIsPqBo9kDGrLZEm6SsWAcTuzX39NuVTKWa2v7VrTT7RBh8zInaJGYI9YIpOxuYZUesN9v38xb5SS0yqbC25YWVL0WDgCYe1nul0wE/4rP9tGJl8nbaxTbUnOs5++0Gcre1pHxgeeMydDmj4yqfIqiNgxn2TpdHaJzVPLuEAwK3cq/dkgGdg8hGfOxGZVZd5AxoBERjiZkf0rGcviAiWmfrPxmaR0jgJPtKyK41l6eEEO4zAe3XzctvqUyUa7352K0lDbI0HxA7H3RChj1u+4GacQ+Vge6Xt07ImpsOrcpRkikBLYEDoIwT8NFeE1BxpWli868Z7iESI+RN7wqZF1liNq4pc8CcfEqoTeNTicu5ISX9Vs4O2Zwk8=
