language: php
matrix:
  include:
  - php: '5.6'
    env: VERSION=7.8.0.1 EDITION=Ent TESTS=7.8
  - php: '5.6'
    env: VERSION=7.7.2.1 EDITION=Ent TESTS=7.7
before_install:
- echo "error_reporting = E_ALL & ~E_NOTICE & ~E_STRICT" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
- sudo apt-get purge elasticsearch
- sudo curl -O https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.4.4.deb
- sudo dpkg -i --force-confnew elasticsearch-1.4.4.deb
- sudo service elasticsearch restart
- curl https://scarlett.sugarondemand.com/custom/hosted/encrypt.tar.gz.enc -o encrypt.tar.gz.enc
- openssl aes-256-cbc -k "$super_secret_password" -in encrypt.tar.gz.enc -out encrypt.tar.gz -d
- tar -xzf encrypt.tar.gz
before_script:
- composer install
- unzip encrypt/Installers/$VERSION/Sugar$EDITION-$VERSION.zip &> /dev/null
- cp -R encrypt/Tests/$TESTS/ Sugar$EDITION-Full-$VERSION/tests/
- cp .travis/config_si.php Sugar$EDITION-Full-$VERSION/config_si.php
- cp .travis/cliSilentInstall.php Sugar$EDITION-Full-$VERSION/cliSilentInstall.php
# try to avoid mysql has gone away errors
- echo -e "[server]\nmax_allowed_packet=1024M\nwait_timeout = 2147483" | sudo tee -a /etc/mysql/my.cnf
- mysql -u root -e "CREATE USER 'sugarcrm'@'localhost' IDENTIFIED BY 'sugarcrm'"
- mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO 'sugarcrm'@'localhost' WITH GRANT OPTION;"
- mysql -u root -e "FLUSH PRIVILEGES;"
- sudo service mysql restart
- mysql -e "SHOW VARIABLES LIKE 'max_allowed_packet';"
- mysql -e "SHOW VARIABLES LIKE 'wait_timeout';"
- mysql -e "SHOW VARIABLES;"
- sudo chmod -R 777 Sugar$EDITION-Full-$VERSION
- mv -f Sugar$EDITION-Full-$VERSION sugar
- cd sugar
- sleep 10
- php cliSilentInstall.php
- sudo chmod -R 777 .
- cd ..
script: travis_wait vendor/bin/phpunit --group support --verbose --debug
env:
  global:
    secure: cE1UK0J/EaVPxSG6qr6NEBYEOuBk+iR0CTlrgibpmJVkOWr34gu+HfsZSh4YvktkKLsGHJu2O4GeIGMAWnic/87+eWpeURXd5w1z14WgYpbDnL1h+TnZhjMJG9FRnmV1/5Krk9NxvIkHBWl3c9FuiCBQ88ZpmRDcxHauefftZoLqqrIq7kmQ7KHUzeWi1tUn7Ft+a56vmdajeGnKkPeLDix9wOeibDj6mDk4CeB5QeMB0APw4pjceAExfYMJcBjBshXD2GblmrW3j7OH4YSgSaYSR5DtRiOv2CjMfIr/jOHqMQn7dJzEIsPqBo9kDGrLZEm6SsWAcTuzX39NuVTKWa2v7VrTT7RBh8zInaJGYI9YIpOxuYZUesN9v38xb5SS0yqbC25YWVL0WDgCYe1nul0wE/4rP9tGJl8nbaxTbUnOs5++0Gcre1pHxgeeMydDmj4yqfIqiNgxn2TpdHaJzVPLuEAwK3cq/dkgGdg8hGfOxGZVZd5AxoBERjiZkf0rGcviAiWmfrPxmaR0jgJPtKyK41l6eEEO4zAe3XzctvqUyUa7352K0lDbI0HxA7H3RChj1u+4GacQ+Vge6Xt07ImpsOrcpRkikBLYEDoIwT8NFeE1BxpWli868Z7iESI+RN7wqZF1liNq4pc8CcfEqoTeNTicu5ISX9Vs4O2Zwk8=
